apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: odoo
type: Opaque
data:
  PGPASSWORD: "ZXhhbXBsZS1kYi1wYXNzd29yZA=="
  ADMIN_PASSWORD: "ZXhhbXBsZS1hZG1pbi1wYXNzd29yZA=="
  SMTP_PASSWORD: ""
