apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: odoo-pvc
    namespace: odoo
  # nfs:
  #   path: "/odoo-fs"
  #   server: "nfs-service.storage.svc.cluster.local"
  local:
    path: /var/opt/kube_pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - bughunter2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: odoo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: odoo-pv
  resources:
    requests:
      storage: 100Gi
